### ISSUE TITLE
User: filter my favoriteRecipes or recipesToCook by type

### ISSUE THREAD

**Issue by edignot** [rachael-t/whats-cookin#3]
As a user I should be able to:
filter my favoriteRecipes or recipesToCook by type

**Comment by rachael-t** [comment]
Data model functionality completed with user.filterRecipes and test is passing.
Still working through bugs with DOM functionality.

**Comment by rachael-t** [comment]
When the user filters their favorite recipes or recipes to cook, and then selects a category tag, ALL recipes matching that selected tag appear, not a filtered version of a saved list.
